### PR TITLE
Find and set the nearest `.scss-lint.yml` config file.

### PR DESCRIPTION
**Pull request by yoodame**
Searches the active file's directory and parent directories for a config file to use. If found, updates the `cmd` variable to specify the location of the config file.

### CODE REVIEW

**Comment by yoodame** [comment]
Hi @adamwalzer, wondering if you had a chance to review/consider this pull request?

**Comment by adamwalzer** [comment]
@yoodame I will look at this tonight. Sorry for the delay. I didn't see the PR.

**Comment by adamwalzer** [comment]
Alright, this PR looks good. I'm just to merge it and then bump the version and update the README and push the new version.

**Comment by adamwalzer** [comment]
@yoodame just so you know, I had to switch find-parent-dir to a dependency instead of a dev dependency. It's not a problem, I just wanted you to know for any future PRs. And thank you so much for this one!

**Pull request merged**
